// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chubin518/kestrel-layout-advanced/internal/routes"
	"github.com/chubin518/kestrel-layout-advanced/internal/routes/handler"
	"github.com/chubin518/kestrel-layout-advanced/internal/service"
	"github.com/chubin518/kestrel-layout-advanced/pkg/config"
	"github.com/chubin518/kestrel-layout-advanced/pkg/logging"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitRoutes(iConfig config.IConfig, iLogging logging.ILogging) func(gin.IRouter) {
	fileService := service.NewFileService()
	fileHandler := handler.NewFileHandler(fileService)
	shellService := service.NewShellService()
	shellHandler := handler.NewShellHandler(shellService)
	v := routes.InitRoutes(fileHandler, shellHandler)
	return v
}

// wire.go:

var ServiceSet = wire.NewSet(service.NewShellService, service.NewFileService)

var HandlerSet = wire.NewSet(handler.NewShellHandler, handler.NewFileHandler)

var RoutesSet = wire.NewSet(routes.InitRoutes)
